CREATE TABLE `invoices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`invoiceId` varchar(255) NOT NULL,
	`externalId` varchar(255) NOT NULL,
	`userId` varchar(255) NOT NULL,
	`status` varchar(255) NOT NULL,
	`merchantName` varchar(255) NOT NULL,
	`merchantProfilePictureUrl` text NOT NULL,
	`amount` int NOT NULL,
	`expiryDate` timestamp NOT NULL,
	`invoiceUrl` text NOT NULL,
	`created` timestamp NOT NULL DEFAULT '2025-03-17 09:58:14.696',
	`updated` timestamp NOT NULL DEFAULT '2025-03-17 09:58:14.696',
	`currency` varchar(255) NOT NULL,
	`customer` json NOT NULL,
	`items` json NOT NULL,
	`fees` json,
	`availableBanks` json,
	`availableRetailOutlets` json,
	`availableEwallets` json,
	`availableQrCodes` json,
	`availableDirectDebits` json,
	`availablePaylaters` json,
	CONSTRAINT `invoices_id` PRIMARY KEY(`id`),
	CONSTRAINT `invoices_invoiceId_unique` UNIQUE(`invoiceId`)
);
